### Course create
POST localhost:8080/course/create
Content-Type: application/json

{
  "name": "Fizika",
  "price": 750.0,
  "duration": "10 oy",
  "createdDate": "2022-09-26"
}

### Course list
GET localhost:8080/course/list
Content-Type: application/json

### Course getById
GET localhost:8080/course/get/2
Content-Type: application/json

### Course update
PUT localhost:8080/course/update/5
Content-Type: application/json

{
  "name": "HTML",
  "price": 200.0,
  "duration": "3 oy",
  "createdDate": "2019-09-10"
}

### Course delete
DELETE localhost:8080/course/delete/3

### Course getByName
GET localhost:8080/course/getByName/Java

### Course getByPrice
GET localhost:8080/course/getByPrice/750

### Course getByDuration
GET localhost:8080/course/getByDuration/3 oy

### Course getByListPriceBetween
GET localhost:8080/course/getCourseListPriceBetween/0.0/1000.0

### Course getByListCrreatedDateBetween
GET localhost:8080/course/getCourseListCreatedDatesBetween/2012-01-01/2024-12-12

### Course getByListPriceBetween
GET localhost:8080/course//0.0/1000.0

### Course paginationById
GET http://localhost:8080/course/pagingById

### Course paginationByCretaedDate
GET http://localhost:8080/course/pagingByCreatedDate

### Course getByListPriceWithCreatedDate
GET localhost:8080/course/pagingByPriceWithCreatedDate/750.0

