### Course create
POST localhost:8080/course/create
Content-Type: application/json

{
  "name": "IELTS",
  "price": 750.0,
  "duration": "18 oy",
  "createdDate": "2022-09-26"
}

### Course list
GET localhost:8080/course/list
Content-Type: application/json

### Course getById
GET localhost:8080/course/get/2
Content-Type: application/json

### Course update
PUT localhost:8080/course/update/1
Content-Type: application/json

{
  "name": "CSS",
  "price": 200.0,
  "duration": "3 oy",
  "createdDate": "2019-09-10"
}

### Course delete
DELETE localhost:8080/course/delete/1

### Course getByName
GET localhost:8080/course/getByName/Java

### Course getByPrice
GET localhost:8080/course/getByPrice/750

### Course getByName
GET localhost:8080/course/getByDuration/18 oy
