### StudentCourse create
POST localhost:8080/student_course/create
Content-Type: application/json

{
  "studentId": 3,
  "courseId": 5,
  "mark": "5"
}

### StudentCourse update
PUT localhost:8080/student_course/update/8
Content-Type: application/json

{
  "studentId": 3,
  "courseId": 5,
  "mark": "2"
}

### StudentCourse getById
GET localhost:8080/student_course/getById/1

### StudentCourseDetail getById
GET http://localhost:8080/student_course/getByIdWithDetail/8

### StudentCourse deleteById
DELETE http://localhost:8080/student_course/deleteById/2

### StudentCourse list
GET http://localhost:8080/student_course/list

### StudenCourse getBycreatedDateMark
GET http://localhost:8080/student_course/student's_mark/2023-04-06/6