### StudentCourse create
POST localhost:8080/student_course/create
Content-Type: application/json

{
  "studentId": 1,
  "courseId": 5,
  "mark": "5"
}

### StudentCourse update
PUT localhost:8080/student_course/update/8
Content-Type: application/json

{
  "studentId": 7,
  "courseId": 5,
  "mark": "2"
}

### StudentCourse getById
GET localhost:8080/student_course/getById/1

### StudentCourseDetail getById
GET http://localhost:8080/student_course/getByIdWithDetail/8

### StudentCourse deleteById
DELETE http://localhost:8080/student_course/deleteById/2

### StudentCourse list
GET http://localhost:8080/student_course/list

### StudentCourse getByDate
GET localhost:8080/student_course/getByDate/3/2023-04-06 15:33:05.905722

### StudentCourse getByBetweenDate
GET localhost:8080/student_course/getBetweenDate?studentId=1&fromDate=2022-01-01&toDate=2022-01-03

### StudentCourse getByAllMark
GET localhost:8080/student_course/getAllMark?studentId=1

### StudentCourse getFirstMark
GET localhost:8080/student_course/getTopMark/1

### StudentCourse getLastMark
GET localhost:8080/student_course/getLastMark/1

### StudentCourse getCourseFirstMark
GET localhost:8080/student_course/getStudentCourseFirstMark?studentId=1&courseId=1

### StudentCourse getCountCourseMark
GET localhost:8080/student_course/countCourseMark?courseId=1

### StudentCourse paging
GET http://localhost:8080/student_course/paging

### StudentCourse paging with student id
GET http://localhost:8080/student_course/pagingByStudentIdWithCreatedDate/1

### StudentCourse paging with course id
GET http://localhost:8080/student_course/pagingByCourseIdWithCreatedDate/2