### Student create
POST localhost:8080/student/create
Content-Type: application/json

{
  "name": "Aliya",
  "surname": "Aliyov",
  "age": 24,
  "birthDate": "1999-08-31",
  "level": 7,
  "gender": "FEMALE"
}
### Student list
GET localhost:8080/student/list
Content-Type: application/json

### Student getById
GET localhost:8080/student/get/3
Content-Type: application/json

### Student updateByid
PUT localhost:8080/student/update/1
Content-Type: application/json

{
 "name": "Alish",
  "surname": "Sadirev",
  "age": 20,
  "birthDate": "2000-12-12",
  "level": 2,
  "gender": "MALE"
}

### Student delete
DELETE localhost:8080/student/delete/4

### Studen getByName
GET localhost:8080/student/getByName/Eshmat

### Studen getBySurame
GET localhost:8080/student/getBySurname/Sadirev

### Studen getByLevel
GET localhost:8080/student/getByLevel/1

### Studen getByAge
GET localhost:8080/student/getByAge/24

### Studen getByGender
GET localhost:8080/student/getByGender/FEMALE